server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

spring:
  cloud:
    config:
      enabled: false

vaadin:
  servlet:
      urlMapping: /ui/*

---

spring:
  profiles: cloud

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST_URL}

#memcache-url: ${MEMCACHE_URL:memcache_url}