server:
  port: ${PORT:9000}

security:
  user:
    password: ${EUREKA_USER_PASSWORD:eureka.password}

spring:
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
